export let initialState = {
        header:{
            menu:[],
            jumboText:{
                quote:{
                    header:'',
                    author:'',
                    PolishLang:{
                        header:''
                    }
                },
                a:{
                    header:'',
                    href:'',
                    PolishLang:{
                        header:''
                    }
                }
            },
        },
        aboutIntro:{
            header:'',
            text:'',
            PolLang:{
                header:'',
                text:'initial'
            }
        },
        stack:{
            header:'',
            tools:[]
        },
        projects:[],
        reactInfo:{},
        
        footer:{
            rightData:[]
        },
        buttons:{
            github:{
                eng:'',
                pl:''
            }
        }
    }