export let initialState = {
        header:{
            menu:[],
            jumboText:{}
        },
        aboutIntro:{
            header:'',
            text:'',
            PolLang:{
                header:'',
                text:'initial'
            }
        },
        projects:[],
        reactInfo:{},
        stack:[],
        footer:{
            rightData:[]
        },
    }