export const ReactComponentData = {
    Header: "why react ?",
    MainText: "I use React because it’s a great tool that lets me combine HTML and JavaScript seamlessly using JSX. It makes building user interfaces much faster and more enjoyable. One of React’s biggest advantages is its efficient rendering and ability to update data instantly without reloading the page, which really improves the overall user experience. Since React is based on reusable components, the code stays clean and easy to maintain even as the project grows. The one-way data flow also helps keep apps predictable and stable. On top of that, React is secure — JSX helps prevent injection and XSS attacks. I also appreciate its huge community and ecosystem, with plenty of ready-to-use libraries, tools, and resources that make development smoother and more creative.",
    Pros: ["Fast Rendering", "JSX", "Stable Code", "Safety", "Maintenance", "One-way data flow", "Facebook Support", "Reusability", "Resources"],
    PolLang: {
        Header: "dlaczego react?",
        MainText: "Używam Reacta, ponieważ to świetne narzędzie, które pozwala płynnie łączyć HTML i JavaScript za pomocą JSX. Sprawia, że budowanie interfejsów użytkownika jest znacznie szybsze i przyjemniejsze. Jedną z największych zalet Reacta jest jego wydajne renderowanie i możliwość natychmiastowej aktualizacji danych bez przeładowania strony, co naprawdę poprawia ogólne doświadczenie użytkownika. Ponieważ React opiera się na komponenach wielokrotnego użytku, kod pozostaje czysty i łatwy w utrzymaniu nawet gdy projekt się rozrasta. Jednokierunkowy przepływ danych również pomaga utrzymać aplikacje przewidywalnymi i stabilnymi. Ponadto React jest bezpieczny — JSX pomaga zapobiegać atakom typu injection i XSS. Doceniam również jego ogromną społeczność i ekosystem, z mnóstwem gotowych do użycia bibliotek, narzędzi i zasobów, które sprawiają, że rozwój jest płynniejszy i bardziej kreatywny.",
        Pros: ["Renderowanie", "JSX", "Stabilny kod", "Bezpieczeństwo", "Łatwe utrzymanie", "Przepływ danych", "Wsparcie Facebooka", "Reużywalność", "Zasoby"]
    }
}